START TRANSACTION;

UPDATE dataentrychange_auditlog
SET Colname = CASE 
    -- salesorderdet_commission_attribute_mstdet
    WHEN Tablename = 'salesorderdet_commission_attribute_mstdet' AND Colname = 'PRICE_EA_INCLUDING_COMMISSION_PRICE' THEN 'unitPrice'
    WHEN Tablename = 'salesorderdet_commission_attribute_mstdet' AND Colname = 'COMMISSION_EA_PERCENTAGE' THEN 'commissionPercentage'
    WHEN Tablename = 'salesorderdet_commission_attribute_mstdet' AND Colname = 'COMMISSION_EA_PRICE' THEN 'commissionValue'
    WHEN Tablename = 'salesorderdet_commission_attribute_mstdet' AND Colname = 'QUOTED_COMMISSION_EA_PERCENTAGE' THEN 'quoted_commissionPercentage'
    WHEN Tablename = 'salesorderdet_commission_attribute_mstdet' AND Colname = 'QUOTED_COMMISSION_EA_PRICE' THEN 'quoted_commissionValue'
    WHEN Tablename = 'salesorderdet_commission_attribute_mstdet' AND Colname = 'QUOTED_PRICE_EA_INCLUDING_COMMISSION_PRICE' THEN 'quoted_unitPrice'
    WHEN Tablename = 'salesorderdet_commission_attribute_mstdet' AND Colname = 'OPEN_PO_QTY' THEN 'poQty'
    WHEN Tablename = 'salesorderdet_commission_attribute_mstdet' AND Colname = 'QUOTED_QTY' THEN 'quotedQty'
    WHEN Tablename = 'salesorderdet_commission_attribute_mstdet' AND Colname = 'TYPE' THEN 'type'
    WHEN Tablename = 'salesorderdet_commission_attribute_mstdet' AND Colname = 'COMMISSION_CALC_FROM' THEN 'commissionCalculateFrom'
    WHEN Tablename = 'salesorderdet_commission_attribute_mstdet' AND Colname = 'SALES_COMMISSION_NOTES' THEN 'salesCommissionNotes'

    -- salesorderdet_commission_attribute
    WHEN Tablename = 'salesorderdet_commission_attribute' AND Colname = 'PRICE_EA_INCLUDING_COMMISSION_PRICE' THEN 'unitPrice'
    WHEN Tablename = 'salesorderdet_commission_attribute' AND Colname = 'COMMISSION_EA_PERCENTAGE' THEN 'commissionPercentage'
    WHEN Tablename = 'salesorderdet_commission_attribute' AND Colname = 'COMMISSION_EA_PRICE' THEN 'commissionValue'
    WHEN Tablename = 'salesorderdet_commission_attribute' AND Colname = 'QUOTED_COMMISSION_EA_PERCENTAGE' THEN 'org_commissionPercentage'
    WHEN Tablename = 'salesorderdet_commission_attribute' AND Colname = 'QUOTED_COMMISSION_EA_PRICE' THEN 'org_commissionValue'
    WHEN Tablename = 'salesorderdet_commission_attribute' AND Colname = 'QUOTED_PRICE_EA_INCLUDING_COMMISSION_PRICE' THEN 'org_unitPrice'

    -- salesorder_otherexpense_details
    WHEN Tablename = 'salesorder_otherexpense_details' AND Colname = 'ASSY_ID_PID' THEN 'partID'
    WHEN Tablename = 'salesorder_otherexpense_details' AND Colname = 'QTY' THEN 'qty'
    WHEN Tablename = 'salesorder_otherexpense_details' AND Colname = 'PRICE' THEN 'price'
    WHEN Tablename = 'salesorder_otherexpense_details' AND Colname = 'CHARGE_FREQUENCY' THEN 'frequency'
    WHEN Tablename = 'salesorder_otherexpense_details' AND Colname = 'COMMENTS' THEN 'lineComment'
    WHEN Tablename = 'salesorder_otherexpense_details' AND Colname = 'INTERNAL_NOTES' THEN 'lineInternalComment'
    WHEN Tablename = 'salesorder_otherexpense_details' AND Colname = 'CHARGE_FREQUENCY_TYPE' THEN 'frequencyType'
    WHEN Tablename = 'salesorder_otherexpense_details' AND Colname = 'OF_RELEASE_NUMBER' THEN 'refReleaseLineID'
    WHEN Tablename = 'salesorder_otherexpense_details' AND Colname = 'DESCRIPTION' THEN 'partDescription'
    WHEN Tablename = 'salesorder_otherexpense_details' AND Colname = 'SPECIAL_NOTES' THEN 'specialNote'
    WHEN Tablename = 'salesorder_otherexpense_details' AND Colname = 'EXTENDED_PRICE' THEN 'extendedPrice'

    -- salesshippingmst
    WHEN Tablename = 'salesshippingmst' AND Colname = 'QTY' THEN 'qty'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'REQUESTED_SHIP_DATE_ORIG' THEN 'shippingDate'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'SHIPPING_METHOD' THEN 'shippingMethodID'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'SHIPPING_ADDRESS' THEN 'shippingAddressID'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'CONTACT_PERSON_SHIPPING_ADDRESS' THEN 'shippingContactPersonID'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'ADDITIONAL_NOTES' THEN 'description'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'RELEASE_NOTES' THEN 'releaseNotes'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'PROMISED_SHIP_DATE_ORIG' THEN 'promisedShipDate'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'SO_LINE_RELEASE_NUMBER' THEN 'releaseNumber'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'REQUESTED_DOCK_DATE_ORIG' THEN 'requestedDockDate'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'CARRIER' THEN 'carrierID'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'CARRIER_ACCOUNT_NUMBER' THEN 'carrierAccountNumber'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'CUST_PO_LINE_RELEASE_NUMBER' THEN 'customerReleaseLine'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'REQUESTED_DOCK_DATE_REVISED' THEN 'revisedRequestedDockDate'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'REQUESTED_SHIP_DATE_REVISED' THEN 'revisedRequestedShipDate'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'PROMISED_SHIP_DATE_REVISED' THEN 'revisedRequestedPromisedDate'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'IS_LOCK_ORIG_DATES' THEN 'isAgreeToShip'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'IS_REL_QTY_READY' THEN 'isReadyToShip'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'RELEASE_PO_NUMBER_BPO_ONLY' THEN 'poReleaseNumber'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'INTERMEDIATE_ADDRESS' THEN 'intermediateShipmentId'
    WHEN Tablename = 'salesshippingmst' AND Colname = 'CONTACT_PERSON_INTERMEDIATE_SHIPPING_ADDRESS' THEN 'intermediateContactPersonID'

    -- salesorderdet
    WHEN Tablename = 'salesorderdet' AND Colname = 'PO_QTY' THEN 'qty'
    WHEN Tablename = 'salesorderdet' AND Colname = 'PRICE' THEN 'price'
    WHEN Tablename = 'salesorderdet' AND Colname = 'EXTENDED_PRICE' THEN 'extendedPrice'
    WHEN Tablename = 'salesorderdet' AND Colname = 'TOT_OTHER_CHARGES_PRICE' THEN 'otherCharges'
    WHEN Tablename = 'salesorderdet' AND Colname = 'MR_PQTY' THEN 'mrpQty'
    WHEN Tablename = 'salesorderdet' AND Colname = 'SHIPPING_QTY' THEN 'shippingQty'
    WHEN Tablename = 'salesorderdet' AND Colname = 'ORIGINAL_PO_QTY' THEN 'originalPOQty'
    WHEN Tablename = 'salesorderdet' AND Colname = 'CUST_CONSIGNED_MATERIAL_PROMISED_DOCK_DATE' THEN 'materialTentitiveDocDate'
    WHEN Tablename = 'salesorderdet' AND Colname = 'PURCHASED_MATERIAL_DOCK_DATE' THEN 'materialDueDate'
    WHEN Tablename = 'salesorderdet' AND Colname = 'REQUESTED_BLANKET_PO_START_DATE' THEN 'requestedBPOStartDate'
    WHEN Tablename = 'salesorderdet' AND Colname = 'BLANKET_PO_END_DATE' THEN 'blanketPOEndDate'
    WHEN Tablename = 'salesorderdet' AND Colname = 'ASSY_ID_PID' THEN 'partID'
    WHEN Tablename = 'salesorderdet' AND Colname = 'PART_TYPE' THEN 'partType'
    WHEN Tablename = 'salesorderdet' AND Colname = 'PART_DESCRIPTION' THEN 'partDescription'
    WHEN Tablename = 'salesorderdet' AND Colname = 'UOM' THEN 'uom'
    WHEN Tablename = 'salesorderdet' AND Colname = 'SO_LINE' THEN 'lineID'
    WHEN Tablename = 'salesorderdet' AND Colname = 'PO_LINE_NUMBER' THEN 'custPOLineNumber'
    WHEN Tablename = 'salesorderdet' AND Colname = 'ORG_PO_LINE_NUMBER' THEN 'custOrgPOLineNumber'
    WHEN Tablename = 'salesorderdet' AND Colname = 'ASSOCIATE_TO_PO' THEN 'refSODetID'
    WHEN Tablename = 'salesorderdet' AND Colname = 'QUOTE_GROUP' THEN 'refRFQGroupID'
    WHEN Tablename = 'salesorderdet' AND Colname = 'QUOTE_QTY_TURN_TIME' THEN 'refRFQQtyTurnTimeID'
    WHEN Tablename = 'salesorderdet' AND Colname = 'QUOTE_NUMBER' THEN 'quoteNumber'
    WHEN Tablename = 'salesorderdet' AND Colname = 'QUOTE_FROM' THEN 'quoteFrom'
    WHEN Tablename = 'salesorderdet' AND Colname = 'BUILD_WEEK' THEN 'prcNumberofWeek'
    WHEN Tablename = 'salesorderdet' AND Colname = 'TENTATIVE_BUILD' THEN 'tentativeBuild'
    WHEN Tablename = 'salesorderdet' AND Colname = 'LINE_STATUS' THEN 'salesOrderDetStatus'
    WHEN Tablename = 'salesorderdet' AND Colname = 'COMPLETE_STATUS_REASON' THEN 'completeStatusReason'
    WHEN Tablename = 'salesorderdet' AND Colname = 'SO_LINE_SHIPPING_STATUS' THEN 'soLineShippingStatus'
    WHEN Tablename = 'salesorderdet' AND Colname = 'IS_HOT_JOB' THEN 'isHotJob'
    WHEN Tablename = 'salesorderdet' AND Colname = 'IS_SO_CANCEL' THEN 'isCancle'
    WHEN Tablename = 'salesorderdet' AND Colname = 'IS_SKIP_KIT_CREATION' THEN 'isSkipKitCreation'
    WHEN Tablename = 'salesorderdet' AND Colname = 'IS_SO_REVISED_PRICE' THEN 'isUnitPriceRevised'
    WHEN Tablename = 'salesorderdet' AND Colname = 'IS_CUSTOMER_CONSIGN' THEN 'isCustomerConsign'
    WHEN Tablename = 'salesorderdet' AND Colname = 'IS_NON_INVENTORY_ITEM' THEN 'isNonInventoryItem'
    WHEN Tablename = 'salesorderdet' AND Colname = 'IS_DO_NOT_ISSUE_COFC' THEN 'isDoNotIssueCofc'
    WHEN Tablename = 'salesorderdet' AND Colname = 'IS_SHIP_AS_NON_INVENTORY' THEN 'isShipAsNonInventory'
    WHEN Tablename = 'salesorderdet' AND Colname = 'IS_LOT_CHARGE_ITEM' THEN 'isLotChargeItem'
    WHEN Tablename = 'salesorderdet' AND Colname = 'IS_TARIFF_APPLICABLE' THEN 'isTariffApplicable'
    WHEN Tablename = 'salesorderdet' AND Colname = 'LINE_SHIPPING_COMMENTS' THEN 'remark'
    WHEN Tablename = 'salesorderdet' AND Colname = 'LINE_INTERNAL_NOTES' THEN 'internalComment'
    WHEN Tablename = 'salesorderdet' AND Colname = 'COMMENTS' THEN 'releaseLevelComment'
    WHEN Tablename = 'salesorderdet' AND Colname = 'WO_COMMENT' THEN 'woComment'
    WHEN Tablename = 'salesorderdet' AND Colname = 'SPECIAL_NOTES' THEN 'specialNote'
    WHEN Tablename = 'salesorderdet' AND Colname = 'CANCEL_REASON' THEN 'cancleReason'
    WHEN Tablename = 'salesorderdet' AND Colname = 'UNDO_CANCELLATION_REASON' THEN 'cancleReason'
    WHEN Tablename = 'salesorderdet' AND Colname = 'SALES_COMMISSION_TO' THEN 'salesCommissionTo'
    WHEN Tablename = 'salesorderdet' AND Colname = 'CHARGE_FREQUENCY' THEN 'frequency'
    WHEN Tablename = 'salesorderdet' AND Colname = 'CHARGE_FREQUENCY_TYPE' THEN 'frequencyType'
    WHEN Tablename = 'salesorderdet' AND Colname = 'OF_RELEASE_NUMBER' THEN 'refSOReleaseLineID'

    -- salesordermst
    WHEN Tablename = 'salesordermst' AND Colname = 'SO_NUMBER' THEN 'salesOrderNumber'
    WHEN Tablename = 'salesordermst' AND Colname = 'PO_NUMBER' THEN 'poNumber'
    WHEN Tablename = 'salesordermst' AND Colname = 'PO_DATE' THEN 'poDate'
    WHEN Tablename = 'salesordermst' AND Colname = 'CUSTOMER' THEN 'customerID'
    WHEN Tablename = 'salesordermst' AND Colname = 'CONTACT_PERSON' THEN 'contactPersonID'
    WHEN Tablename = 'salesordermst' AND Colname = 'BILLING_ADDRESS' THEN 'billingAddress'
    WHEN Tablename = 'salesordermst' AND Colname = 'SHIPPING_ADDRESS' THEN 'shippingAddress'
    WHEN Tablename = 'salesordermst' AND Colname = 'SHIPPING_METHOD' THEN 'shippingMethodID'
    WHEN Tablename = 'salesordermst' AND Colname = 'SO_REVISION' THEN 'revision'
    WHEN Tablename = 'salesordermst' AND Colname = 'SHIPPING_COMMENT' THEN 'shippingComment'
    WHEN Tablename = 'salesordermst' AND Colname = 'INTERNAL_COMMENT' THEN 'internalComment'
    WHEN Tablename = 'salesordermst' AND Colname = 'TERM' THEN 'termsID'
    WHEN Tablename = 'salesordermst' AND Colname = 'SO_DATE' THEN 'soDate'
    WHEN Tablename = 'salesordermst' AND Colname = 'REVISION_CHANGE_NOTE' THEN 'revisionChangeNote'
    WHEN Tablename = 'salesordermst' AND Colname = 'IS_BLANKET_PO' THEN 'isBlanketPO'
    WHEN Tablename = 'salesordermst' AND Colname = 'PO_REVISION' THEN 'poRevision'
    WHEN Tablename = 'salesordermst' AND Colname = 'IS_SO_DELETED' THEN 'isDeleted'
    WHEN Tablename = 'salesordermst' AND Colname = 'IS_RMA_PO' THEN 'isRmaPO'
    WHEN Tablename = 'salesordermst' AND Colname = 'IS_LEGACY_PO' THEN 'isLegacyPO'
    WHEN Tablename = 'salesordermst' AND Colname = 'ORIGINAL_PO_DATE' THEN 'originalPODate'
    WHEN Tablename = 'salesordermst' AND Colname = 'RMA_NUMBER' THEN 'rmaNumber'
    WHEN Tablename = 'salesordermst' AND Colname = 'IS_DEBITED_BY_CUSTOMER' THEN 'isDebitedByCustomer'
    WHEN Tablename = 'salesordermst' AND Colname = 'ORG_PO_NUMBER' THEN 'orgPONumber'
    WHEN Tablename = 'salesordermst' AND Colname = 'IS_REWORK_REQUIRED' THEN 'isReworkRequired'
    WHEN Tablename = 'salesordermst' AND Colname = 'REWORK_PO_NUMBER' THEN 'reworkPONumber'
    WHEN Tablename = 'salesordermst' AND Colname = 'BLANKET_PO_OPTION' THEN 'blanketPOOption'
    WHEN Tablename = 'salesordermst' AND Colname = 'LINK_TO_BLANKET_PO' THEN 'linkToBlanketPO'
    WHEN Tablename = 'salesordermst' AND Colname = 'SO_WORKING_STATUS' THEN 'workingStatus'
    WHEN Tablename = 'salesordermst' AND Colname = 'STATUS' THEN 'subStatus'
    WHEN Tablename = 'salesordermst' AND Colname = 'PO_REVISION_DATE' THEN 'poRevisionDate'
    WHEN Tablename = 'salesordermst' AND Colname = 'SALES_COMMISSION_TO' THEN 'salesCommissionTo'
    WHEN Tablename = 'salesordermst' AND Colname = 'CARRIER' THEN 'carrierID'
    WHEN Tablename = 'salesordermst' AND Colname = 'CARRIER_ACCOUNT_NUMBER' THEN 'carrierAccountNumber'
    WHEN Tablename = 'salesordermst' AND Colname = 'FREE_ON_BOARD' THEN 'freeOnBoardId'
    WHEN Tablename = 'salesordermst' AND Colname = 'SERIAL_NUMBER' THEN 'serialNumber'
    WHEN Tablename = 'salesordermst' AND Colname = 'TOTAL_AMOUNT' THEN 'totalAmount'
    WHEN Tablename = 'salesordermst' AND Colname = 'LINE_TOTAL_AMOUNT' THEN 'lineTotalAmount'
    WHEN Tablename = 'salesordermst' AND Colname = 'LINE_MISC_CHARGE' THEN 'lineMiscCharge'
    WHEN Tablename = 'salesordermst' AND Colname = 'BILLING_CONTACT_PERSON' THEN 'billingContactPerson'
    WHEN Tablename = 'salesordermst' AND Colname = 'SHIPPING_CONTACT_PERSON' THEN 'shippingContactPerson'
    WHEN Tablename = 'salesordermst' AND Colname = 'INTERMEDIATE_ADDRESS' THEN 'intermediateAddress'
    WHEN Tablename = 'salesordermst' AND Colname = 'INTERMEDIATE_CONTACT_PERSON' THEN 'intermediateContactPerson'
    WHEN Tablename = 'salesordermst' AND Colname = 'SO_SHIPPING_STATUS' THEN 'soShippingStatus'

    -- salesorder_plan_detailsmst
    WHEN Tablename = 'salesorder_plan_detailsmst' AND Colname = 'PROMISED_SHIP_QTY_FROM_PO' THEN 'poQty'
    WHEN Tablename = 'salesorder_plan_detailsmst' AND Colname = 'PROMISED_SHIP_DATE' THEN 'poDueDate'
    WHEN Tablename = 'salesorder_plan_detailsmst' AND Colname = 'MATERIAL_DOCK_DATE' THEN 'materialDockDate'
    WHEN Tablename = 'salesorder_plan_detailsmst' AND Colname = 'PLANNED_KIT_AND_BUILD_QTY' THEN 'kitReleaseQty'
    WHEN Tablename = 'salesorder_plan_detailsmst' AND Colname = 'BUILD_LEAD_TIME_BUSINESS DAYS' THEN 'mfrLeadTime'
    WHEN Tablename = 'salesorder_plan_detailsmst' AND Colname = 'PLANNED_KIT RELEASE_DATE' THEN 'kitReleaseDate'
    WHEN Tablename = 'salesorder_plan_detailsmst' AND Colname = 'PLANNED_KIT_NUMBER' THEN 'plannKitNumber'
    WHEN Tablename = 'salesorder_plan_detailsmst' AND Colname = 'ACTUAL_KIT_RELEASE_DATE' THEN 'actualKitReleaseDate'
    WHEN Tablename = 'salesorder_plan_detailsmst' AND Colname = 'RELEASED_BY' THEN 'releasedBy'
    WHEN Tablename = 'salesorder_plan_detailsmst' AND Colname = 'FEASIBILITY_AT_THE_TIME_OF_THE_RELEASE' THEN 'releaseTimeFeasibility'
    WHEN Tablename = 'salesorder_plan_detailsmst' AND Colname = 'KIT_STATUS' THEN 'kitStatus'
    WHEN Tablename = 'salesorder_plan_detailsmst' AND Colname = 'WO_NUMBER' THEN 'woID'
    WHEN Tablename = 'salesorder_plan_detailsmst' AND Colname = 'RELEASED_COMMENT' THEN 'releasedNote'
    WHEN Tablename = 'salesorder_plan_detailsmst' AND Colname = 'KIT_RELEASE_NUMBER' THEN 'releaseKitNumber'
    WHEN Tablename = 'salesorder_plan_detailsmst' AND Colname = 'KIT_RETURN_STATUS' THEN 'kitReturnStatus'
    WHEN Tablename = 'salesorder_plan_detailsmst' AND Colname = 'KIT_RETURN_DATE' THEN 'kitReturnDate'

    ELSE Colname
END
WHERE Tablename IN (
    'salesorderdet_commission_attribute_mstdet',
    'salesorderdet_commission_attribute',
    'salesorder_otherexpense_details',
    'salesshippingmst',
    'salesorderdet',
    'salesordermst',
    'salesorder_plan_detailsmst'
);

-- COMMIT; -- Uncomment to save changes
-- ROLLBACK; -- Uncomment to discard changes
